### ISSUE TITLE
Wrong size of adaptive icon overlay

### ISSUE THREAD

**Issue by brudaswen** [usefulness/easylauncher-gradle-plugin#138]
At least on my device/launcher (One Plus 7T Pro), the generated adaptive icon has some issues. Due to the `72dp` size of the overlay, the overlay does not fill the whole foreground.

![screenshot-1616851191457](https://user-images.githubusercontent.com/790875/112722050-93ac0780-8f07-11eb-92d9-db45c1646804.jpg)

**Comment by mateuszkwiecinski** [comment]
Hello again 😄 
Could you please share more details how to reproduce the issue? i.e. which api level you reproduced this on? Which launcher do you use? I tried at couple of emulators and it seemed to be working.

The `72dp` size was the framework requirement https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive of how big the overlay should be 🤔 I'd be afraid if changing the size doesn't break on some other launchers. If the issue is reproducible only on a single launcher I'd try to report the issue to launcher maintainer first

**Comment by brudaswen** [comment]
Just tested with another launcher and now the text is to big there. Now I understand the scaling. Will have a look again to test a solution that might work in "both" launchers.
