### ISSUE TITLE
Support icons defined in a parent module

### ISSUE THREAD

**Issue by outadoc** [usefulness/easylauncher-gradle-plugin#240]
Let's pretend I have a project structured in modules like this:

```
.
└── app-common
    ├── app-v1
    └── app-v2
```

`app-common` is an Android library. Due to some constraints, I have a separate application module for the v1 and v2 apps. However, these do share the same icons; so these icons are contained in `app-common`'s resources.

When applying the plugin to `app-v1` or `app-v2`, their icons are not transformed. When I look at the logs, it seems as if the plugin only looks for icons in the app modules themselves, not the merged resources.

```
> Task :app-v1:easylauncherFastFrDebug UP-TO-DATE
will process icons: @mipmap/ic_launcher
file or directory '/<redacted>/app-v1/src/fr/res', not found
file or directory '/<redacted>/app-v1/src/fast/res', not found
file or directory '/<redacted>/app-v1/src/fastFr/res', not found
file or directory '/<redacted>/app-v1/src/fastFrDebug/res', not found
```

This seems counter-intuitive since the icons are merged by the AGP and available in both the app modules; I think the plugin should accommodate that use case. The plugin can't be applied to the `app-common` module either, as it lacks the AGP application plugin and easylauncher seems to require it.

I haven't been able to find a workaround, either; symlinks, maybe? But we have a lot of modules like this and I don't really want this mess. 😛 

Thanks in advance. Nice work on this project, I hope we can use it in the future.

**Comment by mateuszkwiecinski** [comment]
Hey @outadoc 👋  
Thanks for the report. Unfortunately, I don't think its feasible, but let me elaborate:
For sure a gradle plugin shouldn't modify files ourside the module it was applied to, that'd be a really bad practice 😛 
The other option is to leverage the fact resources merged at some point, within `application` module, but I can't think of a place where the plugin could plug itself in so it has access to merged resources but before it's too late, before AGP considers them _final_. It would have to happen during mergeXxxYyyResource` otherwise it wouldn't be a reliable step, but I'm nor sure if I can modify task behavior nor I want to rely on AGP's internal implemetation. 🤔 

>The plugin can't be applied to the app-common module either, as it lacks the AGP application plugin and easylauncher seems to require it.

FYI: the plugin can be applied to library module as well ([sample](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/sample/example-library/build.gradle#L2)) - maybe that'll work in your case? 
What do you want to achieve? Having 2 application modules and one shared module with icons - do you want the plugin to generate different overlay for each app, but keep the _"main theme"_ of icon icon?

**Comment by outadoc** [comment]
Thanks a lot for your answer!

Well, scratch all that-- I just tested applying the plugin on the `app-common` module as you suggested, and it seems to work just fine. I'm not sure what I screwed up earlier when it didn't work! I think this should work fine for our needs :) Thanks again.
